### ISSUE TITLE
Never stop loading react-native 0.63.3

### ISSUE THREAD

**Issue by Kladislav** [A-Tokyo/react-native-stripe-checkout-webview#10]

**Comment by A-Tokyo** [comment]
Hey  @Kladislav ! Thanks for opening an issue!

The demo screenshot is indeed from RN 0.63.3 and we are currently using this version as well.

Can you check the logs and see if there's something else preventing the library from loading?
Also if you can reproduce with a demo, that'd be great!

**Comment by Kladislav** [comment]
Ohh, sorry, i find whats wrong. I have this bug when switching stripe to production mode. Idk where to find any error, react-native start clear

**Comment by A-Tokyo** [comment]
All good! @Kladislav! Let me know if you face any issues ( :

**Comment by Kladislav** [comment]
Link to video:  https://streamable.com/22vf8v

**Comment by A-Tokyo** [comment]
Are you sure you're passing the correct PRODUCTION STRIPE_PUBLIC_KEY? @Kladislav

**Comment by pratibhahg** [comment]
im also facing this issue when i use PRODUCTION STRIPE_PUBLIC_KEY cannot able load stripe

**Comment by Kladislav** [comment]
@A-Tokyo yes, its correct.

**Comment by Kladislav** [comment]
Maybe the Stripe no more allowing this way

**Comment by A-Tokyo** [comment]
Thanks for your patience guys, I have identified the issue

Live stripe integrations require https connections which is why they don't work on the simulator.
I will check if this is the case on a real device, if it's not then there's nth to be done here. If it is, then I need to figure out a way to ensure that webview is https.

<img width="998" alt="Screen Shot 2020-11-11 at 2 14 16 AM" src="https://user-images.githubusercontent.com/12428415/98749101-b3f98080-23c3-11eb-9b35-c031d0be8763.png">

**Comment by A-Tokyo** [comment]
@Kladislav @pratibhahg Does this only happen on simulators or on real devices as well?

**Comment by Kladislav** [comment]
Link to video: https://streamable.com/22vf8v

**Comment by arunim2405** [comment]
According to this [thread](https://github.com/react-native-webview/react-native-webview/issues/1317#issuecomment-616077160)
Inserting your backend endpoint instead of baseUrl : '' works for android. Can someone confirm? Also @Kladislav did you have an opportunity to test google pay on android using this package?

**Comment by Kladislav** [comment]
@arunim2405 no, we using react native iap for ios subscription

**Comment by Kladislav** [comment]
@arunim2405 i change the base url to my production api endpoint nothing changes. any ideas?

**Comment by arunim2405** [comment]
@Kladislav are you using https on your backend server?

**Comment by Kladislav** [comment]
@arunim2405 yes, wait do i need to test it only on real device?

**Comment by tkrugg** [comment]
I can confirm this happens both on simulator and real device.

**Comment by arunim2405** [comment]
> I can confirm this happens both on simulator and real device.
> But adding baseURL works on android (even on the simulator)
> 
> I changed the library code to:
> 
> ![image](https://user-images.githubusercontent.com/2982512/99193330-94be7280-2778-11eb-9810-b7c0f2637cc6.png)

You're still passing baseUrl : "" (1st prop of webview), try removing that.

**Comment by arunim2405** [comment]
> I can confirm this happens both on simulator and real device.
> But adding baseURL works on android (even on the simulator)
> 
> I changed the library code to:
> 
> ![image](https://user-images.githubusercontent.com/2982512/99193330-94be7280-2778-11eb-9810-b7c0f2637cc6.png)

I wonder why is it not working for @Kladislav 🤔

**Comment by Kladislav** [comment]
@arunim2405 i use my web front end url(nuxt), my backend url is https://site.com/api, ok i will test it soon

**Comment by Kladislav** [comment]
@arunim2405 what SSL certificate you have? do you use letsencrypt?

**Comment by Kladislav** [comment]
Problem solved. Big thanks @arunim2405 @A-Tokyo

**Comment by arunim2405** [comment]
> Problem solved. Big thanks @arunim2405 @A-Tokyo

Congratulations 🎊 what finally solved the issue?

**Comment by MehuImpero** [comment]
![Simulator Screen Shot - iPhone 11 - 2020-11-20 at 19 24 16](https://user-images.githubusercontent.com/71128664/99807883-1b52c580-2b66-11eb-8722-3c8256b2e4dd.png)

Facing error on

**Comment by arunim2405** [comment]
> ![Simulator Screen Shot - iPhone 11 - 2020-11-20 at 19 24 16](https://user-images.githubusercontent.com/71128664/99807883-1b52c580-2b66-11eb-8722-3c8256b2e4dd.png)
> 
> Stuck in loading

Test mode or production?

**Comment by NeOMakinG** [comment]
Hey

Both for me, test mode and prod mode!

**Comment by MehuImpero** [comment]
> > ![Simulator Screen Shot - iPhone 11 - 2020-11-20 at 19 24 16](https://user-images.githubusercontent.com/71128664/99807883-1b52c580-2b66-11eb-8722-3c8256b2e4dd.png)
> > Stuck in loading
> 
> Test mode or production?

testing mode

**Comment by arunim2405** [comment]
> > > ![Simulator Screen Shot - iPhone 11 - 2020-11-20 at 19 24 16](https://user-images.githubusercontent.com/71128664/99807883-1b52c580-2b66-11eb-8722-3c8256b2e4dd.png)
> > > Stuck in loading
> > 
> > 
> > Test mode or production?
> 
> testing mode

Please ensure that you've enabled stripe checkout in the dashboard and you're following proper steps to generate session id. This issue only occurred in production mode and has been now fixed

**Comment by fakeheal** [comment]
Although, https://github.com/A-Tokyo/react-native-stripe-checkout-webview/commit/54d9537fa4f70f6dba8bd9236e839ca318b4580a resolves this issue, here's a related answer on SO (there's another option of hosting the HTML on your server):
https://stackoverflow.com/questions/64702032/react-native-stripe-card-element-not-displaying-for-live-api-key
