### ISSUE TITLE
[question] What is the recommended behaviour for the onSuccess and onCancel URL?

### ISSUE THREAD

**Issue by MatthewJamesBoyle** [A-Tokyo/react-native-stripe-checkout-webview#100]
Thanks for this library,  have found it really useful.

I am putting together the onSuccess and onCancel URLs now and just wondered how others had implemented them? 

I was going to spin up a small web server that simply showed a web page that simply said "Payment successful!"  and a button to close the web view. Something else I considered is redirecting to a page that just closes the web view automatically (assuming this is possible). What are your thoughts?

**Comment by A-Tokyo** [comment]
Hey!

We use the URLs for logical purposes only. Once the webview matches its URL to successURL -> it calls the `onSuccess` function which you can use to close the browser (same behavior applies to onCancel).

What is crucial is the following: (also in README)
- successUrl must have the query string params `?sc_checkout=success&sc_sid={CHECKOUT_SESSION_ID}`
  - sc_sid is optional - must be the last param - when passed results in sessionId being passed to the onSuccess function
- cancelUrl must have the query string params `?sc_checkout=cancel`
- A simple way to do this is using [url-join](https://www.npmjs.com/package/url-join). eg: `urlJoin(mySuccessUrl, '?sc_checkout=success&sc_sid={CHECKOUT_SESSION_ID}')`.


Let me know if you need further help! ( :

**Comment by MatthewJamesBoyle** [comment]
Thanks for the prompt reply. I read the readme and it still isn't entirely clear to me. 

So does the success URL not really need to exist as long as it matches the criteria you outlined?

**Comment by A-Tokyo** [comment]
@MatthewJamesBoyle It needs to exist. But the react-native library only utilizes the query part of the URL. 

So please provide smth like: `https://yourbackend.com/?sc_checkout=success&sc_sid={CHECKOUT_SESSION_ID}'`

**Comment by MatthewJamesBoyle** [comment]
Thanks for the help so far:
I have the following:
```
    <StripeCheckout
                stripePublicKey={publishableKey}
                checkoutSessionInput={{
                    sessionId: session,
                    successURL: `https://api.moonr.app?sc_checkout=success&sc_sid=${session}`,
                    cancelURL: `https://api.moonr.app?sc_checkout=cancel&sc_sid=${session}`,
                }}
                onSuccess={({checkoutSessionId}) => {
                    console.log(`Stripe checkout session succeeded. session id: ${checkoutSessionId}.`);
                }}
                onCancel={() => {
                    console.log(`Stripe checkout session cancelled.`);
                }}
                onLoadingComplete={() => {
                    console.log(`loading done`);
                }}

            />
```

My successURL and cancelURL are:
```
https://api.moonr.app?sc_checkout=success&sc_sid=cs_test_a13D0t4dReanRUPUwmS6JmpugJC904aXqdX2GG6yHL49JMNSHbJ5mKU39z
https://api.moonr.app?sc_checkout=success&sc_sid=cs_test_a1B99pzYvFUgCsThaqENy4WabvEb4YOapwPGWZikd6cdXjkmSnTDUXI3pq
```

If I use these, I see the "loading..." screen on the checkout.  I don't see any other errors. 

If I remove the successURL and cancelURL parameters completely, the checkout screen loads but obviously after I go through the checkout or press cancel I am redirected to a 404 page. 

Sorry If I'm really missing the mark on this but really appreciate the help.
