### ISSUE TITLE
Styling of global page is impossible

### ISSUE THREAD

**Issue by NeOMakinG** [A-Tokyo/react-native-stripe-checkout-webview#14]
I would suggest to add a <style> block in the head with a param. It would allow us to add some styles to the html attribute etc, like reseting default style (padding of html/body etc)

**Comment by A-Tokyo** [comment]
@NeOMakinG This is by design, Stripe doesn't allow you to do that on the web and neither do we!

You can always propose feature requests to stripe checkout team!

**Comment by NeOMakinG** [comment]
@A-Tokyo I was speaking about the loader global page, we can't reset CSS for example on the global html/body tag, because the only thing we can do is putting style inside the loader block :)

**Comment by A-Tokyo** [comment]
@NeOMakinG I added a `htmlContentHead` prop, but I think it might cause security issues so might remove later.

Why do you think this is crucial? You can't do it on the web. Why do you need to do it on Native?

**Comment by A-Tokyo** [comment]
@NeOMakinG Thanks for the input!

I added a `htmlContentHead` prop, but I think it might cause security issues so might remove later.

Why do you think this is crucial? You can't do it on the web. Why do you need to do it on Native? 🤔  Remember that this script can be used maliciously

**Comment by NeOMakinG** [comment]
Why would it cause security issue ? I don't find why.

- You can't use script from a website to an iframe (Stripe content is inside an iframe right?)
- It's for styling the global page properly, instead of adding negative margin inside your loader component, you are just able to kick default paddings, margins of html element inside the page!

It's not crucial as you've some workaround (but not bests), this is way cleaner don't you think?

**Comment by NeOMakinG** [comment]
I we don't want to give people hands on the initial loading page head, maybe we could at least make it customizable (setting background of the page, padding, flex-box properties...)

**Comment by A-Tokyo** [comment]
@NeOMakinG I get you perspective. I am not sure how it can be used maliciously but I am sure some dedicated hacker can find a way! :D

This library is one of the most sensitive libraries security wise, thus I try to avoid security issues by elimination instead of protection!

I will have a conversation with a few security folks and let you know if anything needs to be updated! So far so good!

Thanks a lot for the proposals! ( :

**Comment by A-Tokyo** [comment]
@NeOMakinG Re customization:

Nice thought! How we do it in our app:

```js
const StripeCheckoutScreen = ({ navigation, route }: Props) => {
  const [isLoading, setIsLoading] = useState(true);
  const { stripeCheckoutComponentProps = {}, navigationTitle } =
    route?.params || {};

  /** set navigation options */
  useNavigationOptions(navigation, {
    title: navigationTitle || 'Stripe Checkout',
  });

  return (
    <View style={styles.flex}>
      {isLoading && <LoadingLayout />}
      <View style={[styles.flex, isLoading && styles.isLoading]}>
        <StripeCheckout
          {...stripeCheckoutComponentProps}
          stripePublicKey={config.STRIPE_PUBLIC_KEY}
          onLoadingComplete={(...args) => {
            setIsLoading(false);
            if (stripeCheckoutComponentProps?.onLoadingComplete) {
              stripeCheckoutComponentProps.onLoadingComplete(...args);
            }
          }}
        />
      </View>
    </View>
  );
};
```

Would this work for you?

**Comment by NeOMakinG** [comment]
You're welcome. Let's keep in touch if you've some discussion about security, but pretty sure nothing's bad there :)

**Comment by NeOMakinG** [comment]
The way you use your library looks like you are seeing the StripeCheckout component loader, after your own loader right ?

**Comment by A-Tokyo** [comment]
@NeOMakinG Exactly, this way I don't have to bother editing the HTML loading page since it never shows up anyway. Do you think this is better than a head script?

**Comment by NeOMakinG** [comment]
This is a nice approach tbh, but it had some complexity that maybe we could get rid of.

What about including this complexity inside your library directly? Where the `htmlContentLoading` prop would be a RN component that you can manipulate as you want

**Comment by NeOMakinG** [comment]
So, the stripe payment page would be shown only after the loader you pass as a prop is finished, but on the StripeCheckout component side

**Comment by A-Tokyo** [comment]
@NeOMakinG Re `including this complexity inside your library directly` It'd be too much work since I render html in the webview not RN.

But I can pass a `loadingComponent` prop that abstracts the logic I wrote above

**Comment by NeOMakinG** [comment]
> But I can pass a `loadingComponent` prop that abstracts the logic I wrote above

This is what I was saying :)

**Comment by NeOMakinG** [comment]
Would you want to work on it @A-Tokyo or can I contribute on this feature?

**Comment by A-Tokyo** [comment]
@NeOMakinG Awesome job on the PR 💪 https://github.com/A-Tokyo/react-native-stripe-checkout-webview/pull/15 Once it's out of the WIP state I'll review 🚀

**Comment by NeOMakinG** [comment]
Hey @A-Tokyo, I'm so sorry it's not going further for the moment, I'm pretty busy with work stuff and other needs... If you want to go further and continue, do it, otherwise we'll have to wait :(

**Comment by A-Tokyo** [comment]
@NeOMakinG All good! (: Thanks for the awesome work! 

It's not urgent, whoever has time first can jump in and finish it 💪
