### ISSUE TITLE
Does not work on the Live

### ISSUE THREAD

**Issue by eresid** [A-Tokyo/react-native-stripe-checkout-webview#2]
Uncaught IntegrationError: Live Stripe.js integrations must use HTTPS

**Comment by A-Tokyo** [comment]
@eresid That's expected from stripe if you're using live key with a simulator. 

It works with the live key on my end on a REAL device from a REAL distribution/adhic build

**Comment by eresid** [comment]
It does not work on the real devices, but this was fixed my problem:
https://github.com/react-native-community/react-native-webview/issues/1317

**Comment by A-Tokyo** [comment]
Thanks for bringing this up! 

Fixed here https://github.com/A-Tokyo/react-native-stripe-checkout-webview/commit/3f59be58bbef313b3d64d7eb6bca6b3461621050 --- Also you can pass `webViewProps` and customize webview 💪
