### ISSUE TITLE
Checkout SessionId could not be found!!!!

### ISSUE THREAD

**Issue by hanks1981** [A-Tokyo/react-native-stripe-checkout-webview#37]
hello, greetings to the community.
I have a problem that when I pass it the public keys and the sessionId (generated in the backend and requested by an API) it returns "Something went wrong ...The specifed Checkout Session could not be found ..... " 
I am working with" react ":" 17.0.1 ", "react-native": "0.63.4", 
and on the web we have the same system set up with the same keys and if it works. 
I think the problem comes at the time of sending the sessionId. 
Thanks and regards.

<img width="749" alt="Captura de pantalla 2021-03-24 a las 15 39 11" src="https://user-images.githubusercontent.com/32703591/112329073-2ace5080-8cb7-11eb-8ca3-13ab51cd9cb2.png">

**Comment by A-Tokyo** [comment]
@hanks1981 weird 🤔 Are you sure that STRIPE_PUBLIC_KEY is set properly? And that it matches the backend's secret key?
