### ISSUE TITLE
The *onSuccess* and *Oncancel* method is not working properly

### ISSUE THREAD

**Issue by suresh1502067** [A-Tokyo/react-native-stripe-checkout-webview#41]
@A-Tokyo  Redirect the new screen after success the "check-out" flow but The "Onsucess" method not triggered properly can you help me to resolve this ?

**Comment by suresh1502067** [comment]
I found the solution, we have pass the "?sc_checkout=success" query to success URL in "stripe.checkout.sessions.create" method.
Once i pass the successful now it's triggered correctly.

**Comment by A-Tokyo** [comment]
@suresh1502067 Yes indeed, you need to pass "?checkout=success". All of the instructions can be found in the Readme 👍🏻
