### ISSUE TITLE
Google pay button is not showing 

### ISSUE THREAD

**Issue by suresh1502067** [A-Tokyo/react-native-stripe-checkout-webview#42]
@A-Tokyo  Google pay button is not showing to me. Is it need any additional  configuration?

**Comment by A-Tokyo** [comment]
Hey @suresh1502067, Google Pay and Apple pay require extra configuration to `react-native-web-view` as can be seen here https://github.com/A-Tokyo/react-native-stripe-checkout-webview#apple-pay-and-google-pay

Good luck!

**Comment by akhilsanker** [comment]
Hi @suresh1502067 ,

Have you solved the issue? If so could you please provide the steps followed.

Thanks
