### ISSUE TITLE
not working for connected account 

### ISSUE THREAD

**Issue by MuhammadTalhaRao** [A-Tokyo/react-native-stripe-checkout-webview#76]
I want customers to directly subscribe to connected account. I initialize the stripe and use StripeCheckout component  to redirect customer to stripe checkout but I get 
"
Something went wrong
The specified checkout session could not be found. This error is likely caused by using wrong api key. Please make sure the api keys you used to initialize stripe.js and create the checkout session are test mode keys from same account
"

I have a similar implementation on web and it works fine. **I have made sure I am using the right apis keys** but error persist

**Comment by A-Tokyo** [comment]
Hey  @MuhammadTalhaRao!

Can you check this out? https://github.com/A-Tokyo/react-native-stripe-checkout-webview/issues/62 Hope it helps! ( : 

It's definitely related to the options passed to the checkout session., remember that you can override these options by passing the `checkoutSessionInput`.
